---

# Disable SWAP
- include_tasks: swap.yml

# Install dependencies
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ca-certificates
    - curl
    - gnupg-agent
  when: ansible_distribution == 'Ubuntu'

# Install K3S Lightweight Kubernetes server
- include_tasks: server.yml
  when: "'k3s_server' in group_names"

# Initialize Nodes
- include_tasks: agent.yml
  when: "'k3s_server' not in group_names"